# Generated by Django 5.0.1 on 2025-11-23 08:30

import apps.financials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.financials.models.pi_upload_path),
        ),
    ]
