# Generated by Django 5.0.1 on 2025-11-22 15:02

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('knitted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dyed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finished_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_metrics', to='orders.order')),
            ],
            options={
                'db_table': 'production_metrics',
                'ordering': ['-date'],
            },
        ),
    ]
