# Generated by Django 5.0.1 on 2025-11-21 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('lab_dip', 'Lab Dip'), ('strike_off', 'Strike-Off'), ('bulk_swatch', 'Bulk Swatch'), ('pp_sample', 'PP Sample')], max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('awb_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='orders.order')),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['-created_at'],
            },
        ),
    ]
