# Generated by Django 5.0.1 on 2025-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.CharField(choices=[('lab_dip', 'Lab Dip'), ('strike_off', 'Strike-Off'), ('bulk_swatch', 'Bulk Swatch'), ('pp_sample', 'PP Sample'), ('hand_loom', 'Hand Loom'), ('presentation', 'Presentation')], max_length=20),
        ),
    ]
