# Generated by Django 5.0.1 on 2025-11-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='samples/attachments/'),
        ),
    ]
