# Generated by Django 5.0.1 on 2025-12-09 10:05

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=apps.authentication.models.profile_picture_upload_path),
        ),
    ]
