# Generated by Django 5.0.1 on 2025-11-01 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('style_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fabric_type', models.CharField(max_length=255)),
                ('fabric_specifications', models.TextField(blank=True, null=True)),
                ('fabric_composition', models.CharField(blank=True, max_length=255, null=True)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finish_type', models.CharField(blank=True, max_length=100, null=True)),
                ('construction', models.CharField(blank=True, max_length=100, null=True)),
                ('mill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mill_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prova_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('color_quantity_breakdown', models.JSONField(blank=True, default=list, null=True)),
                ('colorways', models.JSONField(blank=True, default=list, null=True)),
                ('etd', models.DateField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='upcoming', max_length=20)),
                ('category', models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('archived', 'Archived')], db_index=True, default='upcoming', max_length=20)),
                ('approval_status', models.JSONField(blank=True, default=dict, null=True)),
                ('current_stage', models.CharField(default='Design', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('merchandiser', models.ForeignKey(blank=True, db_column='merchandiser_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['category'], name='orders_categor_43c8f1_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'), models.Index(fields=['merchandiser'], name='orders_merchan_07e2ee_idx')],
            },
        ),
    ]
