# Generated by Django 5.0.1 on 2025-11-02 09:29

import apps.orders.models_document
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.orders.models_document.document_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('category', models.CharField(choices=[('sample', 'Sample Photo'), ('lc', 'LC Document'), ('pi', 'PI Document'), ('test_report', 'Test Report'), ('email', 'Email'), ('other', 'Other')], max_length=50)),
                ('subcategory', models.CharField(blank=True, choices=[('lab_dip', 'Lab Dip'), ('strike_off', 'Strike-Off'), ('quality_test', 'Quality Test'), ('bulk_swatch', 'Bulk Swatch'), ('pp_sample', 'PP Sample')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'category'], name='order_docum_order_i_11b18f_idx'), models.Index(fields=['uploaded_by'], name='order_docum_uploade_71122a_idx')],
            },
        ),
    ]
