# Generated by Django 5.0.1 on 2025-11-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_development', 'In Development'), ('running', 'Running Order'), ('bulk', 'Bulk'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='upcoming', max_length=20),
        ),
    ]
