# Generated by Django 5.0.1 on 2025-11-25 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_style_number', models.CharField(max_length=100)),
                ('style_number', models.CharField(db_index=True, max_length=150)),
                ('fabric_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fabric_specifications', models.TextField(blank=True, null=True)),
                ('fabric_composition', models.CharField(blank=True, max_length=255, null=True)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finish_type', models.CharField(blank=True, max_length=100, null=True)),
                ('construction', models.CharField(blank=True, max_length=100, null=True)),
                ('etd', models.DateField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Style',
                'verbose_name_plural': 'Order Styles',
                'db_table': 'order_styles',
                'ordering': ['style_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_code', models.CharField(db_index=True, max_length=100)),
                ('color_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('etd', models.DateField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('mill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mill_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prova_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, help_text='Commission amount or percentage', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('approval_status', models.JSONField(blank=True, default=dict, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='orders.orderstyle')),
            ],
            options={
                'verbose_name': 'Order Color',
                'verbose_name_plural': 'Order Colors',
                'db_table': 'order_colors',
                'ordering': ['color_code'],
            },
        ),
        migrations.AddIndex(
            model_name='orderstyle',
            index=models.Index(fields=['order', 'style_number'], name='order_style_order_i_72e2b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderstyle',
            constraint=models.UniqueConstraint(fields=('order', 'style_number'), name='unique_style_per_order'),
        ),
        migrations.AddIndex(
            model_name='ordercolor',
            index=models.Index(fields=['style', 'color_code'], name='order_color_style_i_d0a517_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordercolor',
            constraint=models.UniqueConstraint(fields=('style', 'color_code'), name='unique_color_code_per_style'),
        ),
    ]
