# Generated by Django 5.0.1 on 2025-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstyle_ordercolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstyle',
            name='base_style_number',
        ),
        migrations.AddField(
            model_name='order',
            name='base_style_number',
            field=models.CharField(blank=True, help_text='Base style number for auto-generating style variants', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderstyle',
            name='cuttable_width',
            field=models.CharField(blank=True, help_text='Cuttable width specification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderstyle',
            name='description',
            field=models.TextField(blank=True, help_text='Style description', null=True),
        ),
        migrations.AlterField(
            model_name='ordercolor',
            name='color_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderstyle',
            name='construction',
            field=models.TextField(blank=True, help_text='Construction details including width and other info', null=True),
        ),
    ]
