# Generated by Django 5.0.1 on 2025-11-25 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderstyle_base_style_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(help_text='Actual delivery date (defaults to ETD)')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, help_text='Quantity delivered by supplier', max_digits=10)),
                ('unit', models.CharField(default='meters', help_text='Unit of measurement', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this delivery', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_deliveries', to='orders.order')),
            ],
            options={
                'verbose_name': 'Supplier Delivery',
                'verbose_name_plural': 'Supplier Deliveries',
                'db_table': 'supplier_deliveries',
                'ordering': ['-delivery_date', '-created_at'],
                'indexes': [models.Index(fields=['order', 'delivery_date'], name='supplier_de_order_i_1c38f7_idx'), models.Index(fields=['delivery_date'], name='supplier_de_deliver_d8e060_idx')],
            },
        ),
    ]
