# Generated by Django 5.0.1 on 2025-11-25 10:18

import uuid
from django.db import migrations, models


def generate_uids(apps, schema_editor):
    """Generate UIDs for existing orders"""
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.uid = uuid.uuid4()
        order.save(update_fields=['uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_supplierdelivery'),
    ]

    operations = [
        # Step 1: Add uid field as nullable first
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.UUIDField(null=True, blank=True, editable=False, help_text='Internal unique identifier for this order'),
        ),
        # Step 2: Populate existing records with UIDs
        migrations.RunPython(generate_uids, reverse_code=migrations.RunPython.noop),
        # Step 3: Make uid non-nullable and unique
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.UUIDField(unique=True, editable=False, db_index=True, help_text='Internal unique identifier for this order'),
        ),
        # Step 4: Add CAD field
        migrations.AddField(
            model_name='order',
            name='cad',
            field=models.CharField(blank=True, max_length=255, null=True, help_text='CAD reference or identifier'),
        ),
        # Step 5: Remove unique constraint from order_number
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50, help_text='PO (Purchase Order) number - can have duplicates'),
        ),
    ]
