# Generated by Django 5.0.1 on 2025-11-26 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20251125_1618'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdelivery',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Optional: Color this delivery is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='orders.ordercolor'),
        ),
        migrations.AddField(
            model_name='supplierdelivery',
            name='style',
            field=models.ForeignKey(blank=True, help_text='Optional: Style this delivery is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='orders.orderstyle'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uid'], name='orders_uid_ee5d7e_idx'),
        ),
    ]
