# Generated by Django 5.0.1 on 2025-11-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_supplierdelivery_color_supplierdelivery_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('sample', 'Sample Photo'), ('lc', 'LC Document'), ('pi', 'PI Document'), ('email', 'Email'), ('other', 'Other')], max_length=50),
        ),
    ]
