# Generated by Django 5.0.1 on 2025-11-26 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_test_report_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_type', models.CharField(choices=[('labDip', 'Lab Dip'), ('strikeOff', 'Strike-Off'), ('handloom', 'Handloom'), ('ppSample', 'PP Sample'), ('quality', 'Quality'), ('price', 'Price')], max_length=20)),
                ('status', models.CharField(choices=[('submission', 'Submission'), ('resubmission', 'Re-submission'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Approval History',
                'verbose_name_plural': 'Approval Histories',
                'db_table': 'approval_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'approval_type'], name='approval_hi_order_i_a64410_idx'), models.Index(fields=['created_at'], name='approval_hi_created_2d921c_idx')],
            },
        ),
    ]
