# Generated by Django 5.0.1 on 2025-11-26 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_approvalhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='approval_type',
            field=models.CharField(choices=[('labDip', 'Lab Dip'), ('strikeOff', 'Strike-Off'), ('handloom', 'Handloom'), ('ppSample', 'PP Sample'), ('quality', 'Quality'), ('price', 'Price'), ('aop', 'AOP'), ('qualityTest', 'Quality Test'), ('bulkSwatch', 'Bulk Swatch')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_code', models.CharField(blank=True, db_index=True, help_text='Color code for this line (optional)', max_length=100, null=True)),
                ('color_name', models.CharField(blank=True, help_text='Color name (optional)', max_length=255, null=True)),
                ('cad_code', models.CharField(blank=True, db_index=True, help_text='CAD code for this line (optional)', max_length=100, null=True)),
                ('cad_name', models.CharField(blank=True, help_text='CAD name or description (optional)', max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity for this specific line', max_digits=10)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('mill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mill_price', models.DecimalField(blank=True, decimal_places=2, help_text='Mill price per unit for this line', max_digits=10, null=True)),
                ('prova_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prova price per unit for this line', max_digits=10, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, help_text='Commission amount per unit for this line', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('etd', models.DateField(blank=True, help_text='Estimated Time of Departure for this line', null=True)),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival for this line', null=True)),
                ('submission_date', models.DateField(blank=True, help_text='Submission date for this line', null=True)),
                ('approval_date', models.DateField(blank=True, help_text='Overall approval date for this line', null=True)),
                ('approval_status', models.JSONField(blank=True, default=dict, help_text='Approval status for each gate at this line level', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('style', models.ForeignKey(help_text='Parent style for this line', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.orderstyle')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
                'db_table': 'order_lines',
                'ordering': ['style', 'color_code', 'cad_code'],
            },
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='order_line',
            field=models.ForeignKey(blank=True, help_text='If set, this approval is specific to this order line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='orders.orderline'),
        ),
        migrations.AddIndex(
            model_name='approvalhistory',
            index=models.Index(fields=['order_line', 'approval_type'], name='approval_hi_order_l_d4f36c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['style', 'color_code'], name='order_lines_style_i_194569_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['style', 'cad_code'], name='order_lines_style_i_1791fa_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['style', 'color_code', 'cad_code'], name='order_lines_style_i_d97b0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('style', 'color_code', 'cad_code'), name='unique_line_combination'),
        ),
    ]
