# Generated by Django 5.0.1 on 2025-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_approvalhistory_approval_type_orderline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_development', 'In Development'), ('running', 'Running Order'), ('bulk', 'Bulk'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='upcoming', help_text='Status of this specific order line', max_length=20),
        ),
    ]
