# Generated by Django 5.0.1 on 2025-11-26 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order_line',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific order line (style+color+CAD) this document is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='supplierdelivery',
            name='order_line',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific order line (style+color+CAD) this delivery is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='orders.orderline'),
        ),
    ]
