# Generated by Django 5.0.1 on 2025-11-28 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_document_order_line_supplierdelivery_order_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='order_line',
            field=models.ForeignKey(blank=True, help_text='If set, this approval is specific to this order line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_history', to='orders.orderline'),
        ),
    ]
