# Generated by Django 5.0.1 on 2025-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_approval_history_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstyle',
            name='finishing_width',
            field=models.CharField(blank=True, help_text='Finishing width specification', max_length=100, null=True),
        ),
    ]
