# Generated by Django 5.0.1 on 2025-12-01 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderstyle_finishing_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bulk_size_set_date',
            field=models.DateField(blank=True, help_text='Bulk Size Set Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cutting_complete_date',
            field=models.DateField(blank=True, help_text='Cutting Complete Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cutting_start_date',
            field=models.DateField(blank=True, help_text='Cutting Start Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dyeing_complete_date',
            field=models.DateField(blank=True, help_text='Date when dyeing was completed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dyeing_start_date',
            field=models.DateField(blank=True, help_text='Dyeing Start Date (Knitting Start + 5 days)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ex_factory_date',
            field=models.DateField(blank=True, help_text='Ex-Factory Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='final_inspection_date',
            field=models.DateField(blank=True, help_text='Final Inspection Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fit_cum_pp_comments_date',
            field=models.DateField(blank=True, help_text='FIT CUM PP Comments Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fit_cum_pp_submit_date',
            field=models.DateField(blank=True, help_text='FIT CUM PP Submit Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='knitting_complete_date',
            field=models.DateField(blank=True, help_text='Knitting Complete Date (Knitting Start + 18 days)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='knitting_start_date',
            field=models.DateField(blank=True, help_text='Knitting Start Date (Yarn Received + 11 days)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('foreign', 'Foreign'), ('local', 'Local')], db_index=True, default='foreign', help_text='Type of order - Foreign or Local', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='packing_complete_date',
            field=models.DateField(blank=True, help_text='Packing Complete Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pp_yards',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PP Yards', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='print_received_date',
            field=models.DateField(blank=True, help_text='Print Received Date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='print_send_date',
            field=models.DateField(blank=True, help_text='Print Send Date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sewing_finish_date',
            field=models.DateField(blank=True, help_text='Sewing Finish Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sewing_input_date',
            field=models.DateField(blank=True, help_text='Sewing Input Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='yarn_booked_date',
            field=models.DateField(blank=True, help_text='Date when yarn was booked', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='yarn_received_date',
            field=models.DateField(blank=True, help_text='Date when yarn was received', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='yarn_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yarn required amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(default='yards', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercolor',
            name='unit',
            field=models.CharField(default='yards', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit',
            field=models.CharField(default='yards', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_order_t_836422_idx'),
        ),
    ]
