# Generated by Django 5.0.1 on 2025-12-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_add_order_type_and_local_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='bulk_size_set_date',
            field=models.DateField(blank=True, help_text='Bulk Size Set Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='cutting_complete_date',
            field=models.DateField(blank=True, help_text='Cutting Complete Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='cutting_start_date',
            field=models.DateField(blank=True, help_text='Cutting Start Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='dyeing_complete_date',
            field=models.DateField(blank=True, help_text='Date when dyeing was completed', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='dyeing_start_date',
            field=models.DateField(blank=True, help_text='Dyeing Start Date (Knitting Start + 5 days)', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='ex_factory_date',
            field=models.DateField(blank=True, help_text='Ex-Factory Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='final_inspection_date',
            field=models.DateField(blank=True, help_text='Final Inspection Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='fit_cum_pp_comments_date',
            field=models.DateField(blank=True, help_text='FIT CUM PP Comments Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='fit_cum_pp_submit_date',
            field=models.DateField(blank=True, help_text='FIT CUM PP Submit Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='knitting_complete_date',
            field=models.DateField(blank=True, help_text='Knitting Complete Date (Knitting Start + 18 days)', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='knitting_start_date',
            field=models.DateField(blank=True, help_text='Knitting Start Date (Yarn Received + 11 days)', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='packing_complete_date',
            field=models.DateField(blank=True, help_text='Packing Complete Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='pp_yards',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PP Yards', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='print_received_date',
            field=models.DateField(blank=True, help_text='Print Received Date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='print_send_date',
            field=models.DateField(blank=True, help_text='Print Send Date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='sewing_finish_date',
            field=models.DateField(blank=True, help_text='Sewing Finish Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='sewing_input_date',
            field=models.DateField(blank=True, help_text='Sewing Input Date', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='yarn_booked_date',
            field=models.DateField(blank=True, help_text='Date when yarn was booked', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='yarn_received_date',
            field=models.DateField(blank=True, help_text='Date when yarn was received', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='yarn_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yarn required amount for this line', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity for this specific line', max_digits=10, null=True),
        ),
    ]
