# Generated by Django 5.0.1 on 2025-12-02 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_add_local_order_fields_to_orderline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('knitting', 'Knitting'), ('dyeing', 'Dyeing'), ('finishing', 'Finishing')], db_index=True, help_text='Type of production entry', max_length=20)),
                ('entry_date', models.DateField(help_text='Date of this production entry')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity processed', max_digits=10)),
                ('unit', models.CharField(default='kg', help_text='Unit of measurement (kg, yards, meters, etc.)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this entry', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entries', to='orders.order')),
                ('order_line', models.ForeignKey(blank=True, help_text='Optional: Specific order line (style+color+CAD) this entry is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to='orders.orderline')),
            ],
            options={
                'verbose_name': 'Production Entry',
                'verbose_name_plural': 'Production Entries',
                'db_table': 'production_entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['order', 'entry_type'], name='production__order_i_6b400b_idx'), models.Index(fields=['order', 'entry_date'], name='production__order_i_e8d43c_idx'), models.Index(fields=['entry_type', 'entry_date'], name='production__entry_t_8c011b_idx'), models.Index(fields=['order_line', 'entry_type'], name='production__order_l_a0313d_idx')],
            },
        ),
    ]
