# Generated by Django 5.0.1 on 2025-12-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_productionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='greige_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated greige quantity (finished fabric + process loss)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='mixed_fabric_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of mixed fabric in greige (e.g., 4 for 4%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='mixed_fabric_type',
            field=models.CharField(blank=True, help_text='Name of mixed fabric (e.g., lycra, spandex)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='process_loss_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Process loss percentage from finished fabric to greige (e.g., 10 for 10%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='yarn_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated yarn required (greige minus mixed fabric portion)', max_digits=10, null=True),
        ),
    ]
