# Generated by Django 5.0.1 on 2025-12-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_add_greige_yarn_calculation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['created_at'], 'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, help_text='Date associated with the document (e.g., LC issue date, PI date)', null=True),
        ),
    ]
