# Generated by Django 5.0.1 on 2025-12-05 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_orderline_options_document_document_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['style', 'color_code', 'cad_code'], 'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_date',
        ),
        migrations.CreateModel(
            name='MillOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mill_name', models.CharField(help_text='Name of the mill offering the price', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit offered by the mill', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency of the price', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this offer', null=True)),
                ('order_line', models.ForeignKey(help_text='Order line this mill offer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mill_offers', to='orders.orderline')),
            ],
            options={
                'verbose_name': 'Mill Offer',
                'verbose_name_plural': 'Mill Offers',
                'db_table': 'mill_offers',
                'ordering': ['mill_name'],
            },
        ),
    ]
