# Generated by Django 5.0.1 on 2025-12-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_milloffer_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, help_text='Date when the document was received/issued (defaults to upload date if not specified)', null=True),
        ),
    ]
