# Generated by Django 5.0.1 on 2025-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_add_document_date_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['style', 'sequence_number', 'created_at'], 'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.AddField(
            model_name='orderline',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='Order of this line within the style (for maintaining insertion order)'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='swatch_received_date',
            field=models.DateField(blank=True, help_text='Date when swatch was received', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='swatch_sent_date',
            field=models.DateField(blank=True, help_text='Date when swatch was sent', null=True),
        ),
    ]
