# Generated by Django 5.0.1 on 2025-12-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_add_swatch_dates_and_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['sequence_number', 'created_at'], 'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.AlterModelOptions(
            name='orderstyle',
            options={'ordering': ['sequence_number', 'created_at'], 'verbose_name': 'Order Style', 'verbose_name_plural': 'Order Styles'},
        ),
        migrations.AddField(
            model_name='orderstyle',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='Order of this style within the order (for maintaining insertion order)'),
        ),
    ]
