# Generated by Django 5.0.1 on 2025-12-08 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_add_style_sequence_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', help_text='User who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for deletion request', null=True)),
                ('response_note', models.TextField(blank=True, help_text='Optional note from approver when approving/declining', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the request was approved or declined', null=True)),
                ('approver', models.ForeignKey(help_text='User who must approve the deletion (order owner)', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order that is requested to be deleted', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='orders.order')),
                ('requester', models.ForeignKey(help_text='User who requested the deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion Request',
                'verbose_name_plural': 'Deletion Requests',
                'db_table': 'deletion_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='deletion_re_status_799845_idx'), models.Index(fields=['requester'], name='deletion_re_request_88186d_idx'), models.Index(fields=['approver'], name='deletion_re_approve_40b480_idx')],
            },
        ),
    ]
