# Generated by Django 5.0.1 on 2025-12-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_add_order_created_by_and_deletion_request'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderstyle',
            name='unique_style_per_order',
        ),
    ]
