# Generated by Django 5.0.1 on 2025-12-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_unique_style_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bulk_size_set_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cutting_complete_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cutting_start_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dyeing_complete_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dyeing_start_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ex_factory_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_inspection_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fit_cum_pp_comments_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fit_cum_pp_submit_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='knitting_complete_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='knitting_start_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packing_complete_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pp_yards',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_received_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_send_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sewing_finish_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sewing_input_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='yarn_booked_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='yarn_received_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='yarn_required',
        ),
    ]
