# Generated by Django 5.0.1 on 2025-12-24 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_remove_production_fields_from_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApprovalGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for the custom approval gate', max_length=100)),
                ('gate_key', models.CharField(help_text='Unique key for this gate (auto-generated from name)', max_length=120)),
                ('status', models.CharField(choices=[('default', 'Default'), ('submission', 'Submission'), ('resubmission', 'Re-submission'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='default', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_gates', to=settings.AUTH_USER_MODEL)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_approval_gates', to='orders.orderline')),
            ],
            options={
                'verbose_name': 'Custom Approval Gate',
                'verbose_name_plural': 'Custom Approval Gates',
                'db_table': 'custom_approval_gates',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order_line', 'gate_key'], name='custom_appr_order_l_2d0bd2_idx')],
                'unique_together': {('order_line', 'gate_key')},
            },
        ),
    ]
