# Generated by Django 5.0.1 on 2026-01-18 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_custom_approval_gate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('general', 'General Update'), ('production', 'Production Update'), ('quality', 'Quality Note'), ('communication', 'Communication'), ('milestone', 'Milestone'), ('issue', 'Issue/Problem'), ('plan', 'Plan/Schedule')], default='general', max_length=20)),
                ('content', models.TextField(help_text='The update/note content')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='orders.order')),
                ('order_line', models.ForeignKey(blank=True, help_text='If set, this log entry is specific to this order line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='orders.orderline')),
            ],
            options={
                'verbose_name': 'Order Activity Log',
                'verbose_name_plural': 'Order Activity Logs',
                'db_table': 'order_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='order_activ_order_i_537ff8_idx'), models.Index(fields=['order_line', 'created_at'], name='order_activ_order_l_4cd0d1_idx'), models.Index(fields=['category'], name='order_activ_categor_4b0be8_idx')],
            },
        ),
    ]
