# Generated by Django 5.0 on 2026-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_orderactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished_fabric_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Finished fabric quantity for local orders (used for production calculations instead of order quantity)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='finished_fabric_unit',
            field=models.CharField(blank=True, help_text='Unit for finished fabric quantity (e.g., kg, yards, meters)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='finished_fabric_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Finished fabric quantity for local orders (used for production calculations instead of line quantity)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='finished_fabric_unit',
            field=models.CharField(blank=True, help_text='Unit for finished fabric quantity (e.g., kg, yards, meters)', max_length=20, null=True),
        ),
    ]
