# Generated by Django 5.0.1 on 2026-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_order_greige_quantity_order_mixed_fabric_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='produced_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of pieces already produced (for garment orders)', null=True),
        ),
    ]
